// <auto-generated />
using System;
using ContratosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContratosAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ContratosAPI.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CondicoesPagamento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("condicoes_pagamento");

                    b.Property<int>("ContraenteId")
                        .HasColumnType("int")
                        .HasColumnName("contraente_id");

                    b.Property<int>("ContratanteId")
                        .HasColumnType("int")
                        .HasColumnName("contratante_id");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_emissao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("descricao");

                    b.Property<decimal>("Precificacao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precificacao");

                    b.Property<int>("StatusContratoId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int>("TipoContraenteId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_contraente_id");

                    b.Property<int>("TipoContratoId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_contrato_id");

                    b.Property<DateTime?>("Validade")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("validade");

                    b.HasKey("Id");

                    b.HasIndex("ContratanteId");

                    b.HasIndex("StatusContratoId");

                    b.HasIndex("TipoContraenteId");

                    b.HasIndex("TipoContratoId");

                    b.ToTable("Contrato", (string)null);
                });

            modelBuilder.Entity("ContratosAPI.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("setor");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("ContratosAPI.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("Estado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Acre",
                            Sigla = "AC"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Alagoas",
                            Sigla = "AL"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Amapá",
                            Sigla = "AP"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Amazonas",
                            Sigla = "AM"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Bahia",
                            Sigla = "BA"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Ceará",
                            Sigla = "CE"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Distrito Federal",
                            Sigla = "DF"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Espírito Santo",
                            Sigla = "ES"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Goiás",
                            Sigla = "GO"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Maranhão",
                            Sigla = "MA"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Mato Grosso",
                            Sigla = "MT"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Mato Grosso do Sul",
                            Sigla = "MS"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Minas Gerais",
                            Sigla = "MG"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Pará",
                            Sigla = "PA"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Paraíba",
                            Sigla = "PB"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Paraná",
                            Sigla = "PR"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Pernambuco",
                            Sigla = "PE"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Piauí",
                            Sigla = "PI"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Rio de Janeiro",
                            Sigla = "RJ"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Rio Grande do Norte",
                            Sigla = "RN"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Rio Grande do Sul",
                            Sigla = "RS"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Rondônia",
                            Sigla = "RO"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Roraima",
                            Sigla = "RR"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Santa Catarina",
                            Sigla = "SC"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "São Paulo",
                            Sigla = "SP"
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Sergipe",
                            Sigla = "SE"
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Tocantins",
                            Sigla = "TO"
                        });
                });

            modelBuilder.Entity("ContratosAPI.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("funcao");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nome_completo");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Funcionario", (string)null);
                });

            modelBuilder.Entity("ContratosAPI.Models.StatusContrato", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("StatusContrato", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Contrato em vigor",
                            Nome = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Contrato finalizado normalmente",
                            Nome = "Encerrado"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Contrato rescindido",
                            Nome = "Rescindido"
                        });
                });

            modelBuilder.Entity("ContratosAPI.Models.TipoContraente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TipoContraente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Pessoa Jurídica",
                            Nome = "Empresa"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Pessoa Física",
                            Nome = "Funcionário"
                        });
                });

            modelBuilder.Entity("ContratosAPI.Models.TipoContrato", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("TipoContrato", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Consolidação das Leis do Trabalho",
                            Nome = "CLT"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Microempreendedor Individual",
                            Nome = "MEI"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Contrato Temporário",
                            Nome = "Temporário"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Profissional Autônomo",
                            Nome = "Autônomo"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Contrato de Estágio",
                            Nome = "Estágio"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Jovem ou menor Aprendiz",
                            Nome = "Aprendiz"
                        });
                });

            modelBuilder.Entity("ContratosAPI.Models.Contrato", b =>
                {
                    b.HasOne("ContratosAPI.Models.Empresa", "Contratante")
                        .WithMany("ContratosComoContratante")
                        .HasForeignKey("ContratanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContratosAPI.Models.StatusContrato", "StatusContrato")
                        .WithMany("Contratos")
                        .HasForeignKey("StatusContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContratosAPI.Models.TipoContraente", "TipoContraente")
                        .WithMany("Contratos")
                        .HasForeignKey("TipoContraenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContratosAPI.Models.TipoContrato", "TipoContrato")
                        .WithMany("Contratos")
                        .HasForeignKey("TipoContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contratante");

                    b.Navigation("StatusContrato");

                    b.Navigation("TipoContraente");

                    b.Navigation("TipoContrato");
                });

            modelBuilder.Entity("ContratosAPI.Models.Empresa", b =>
                {
                    b.OwnsOne("ContratosAPI.Models.CidadeEstado", "CidadeEstado", b1 =>
                        {
                            b1.Property<int>("EmpresaId")
                                .HasColumnType("int");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("cidade");

                            b1.Property<int>("EstadoId")
                                .HasColumnType("int")
                                .HasColumnName("estado_id");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("Empresa");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.OwnsOne("ContratosAPI.Models.Contato", "Contato", b1 =>
                        {
                            b1.Property<int>("EmpresaId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("varchar(254)")
                                .HasColumnName("email");

                            b1.Property<string>("LinkedIn")
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("linkedin");

                            b1.Property<string>("Telefone")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("varchar(14)")
                                .HasColumnName("telefone");

                            b1.Property<string>("TelefoneAlternativo")
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("telefone_alternativo");

                            b1.Property<string>("Website")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("website");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("Empresa");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId");
                        });

                    b.Navigation("CidadeEstado")
                        .IsRequired();

                    b.Navigation("Contato")
                        .IsRequired();
                });

            modelBuilder.Entity("ContratosAPI.Models.Funcionario", b =>
                {
                    b.OwnsOne("ContratosAPI.Models.CidadeEstado", "CidadeEstado", b1 =>
                        {
                            b1.Property<int>("FuncionarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("cidade");

                            b1.Property<int>("EstadoId")
                                .HasColumnType("int")
                                .HasColumnName("estado_id");

                            b1.HasKey("FuncionarioId");

                            b1.ToTable("Funcionario");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioId");
                        });

                    b.OwnsOne("ContratosAPI.Models.Contato", "Contato", b1 =>
                        {
                            b1.Property<int>("FuncionarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("varchar(254)")
                                .HasColumnName("email");

                            b1.Property<string>("LinkedIn")
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("linkedin");

                            b1.Property<string>("Telefone")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("varchar(14)")
                                .HasColumnName("telefone");

                            b1.Property<string>("TelefoneAlternativo")
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("telefone_alternativo");

                            b1.Property<string>("Website")
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("website");

                            b1.HasKey("FuncionarioId");

                            b1.ToTable("Funcionario");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioId");
                        });

                    b.Navigation("CidadeEstado")
                        .IsRequired();

                    b.Navigation("Contato")
                        .IsRequired();
                });

            modelBuilder.Entity("ContratosAPI.Models.Empresa", b =>
                {
                    b.Navigation("ContratosComoContratante");
                });

            modelBuilder.Entity("ContratosAPI.Models.StatusContrato", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("ContratosAPI.Models.TipoContraente", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("ContratosAPI.Models.TipoContrato", b =>
                {
                    b.Navigation("Contratos");
                });
#pragma warning restore 612, 618
        }
    }
}
